"use client";

import { useState } from "react";

interface Props {
  agentId: string | null;
  agentUrl: string | null;
  isLoading: boolean;
  onLaunch: () => void;
  errorMessage?: string | null;
  intakeSummary?: { symptoms: string; severity: string; duration: string };
  chatMessages?: { role: string; content: string }[];
}

interface Summary {
  chiefComplaint: string;
  keySymptoms: string[];
  recommendations: string[];
  followUp: string;
  urgency: "low" | "medium" | "high";
}

export default function VideoAgent({ agentId, agentUrl, isLoading, onLaunch, errorMessage, intakeSummary, chatMessages }: Props) {
  const [showSummary, setShowSummary] = useState(false);
  const [summary, setSummary] = useState<Summary | null>(null);
  const [generating, setGenerating] = useState(false);

  const urgencyColor = { low: "#22c55e", medium: "#f59e0b", high: "#ef4444" };

  const handleEndCall = async () => {
    setGenerating(true);
    setShowSummary(true);

    try {
      const res = await fetch("/api/conversation", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          messages: [
            {
              role: "user",
              content: `Generate a post-consultation summary based on:
Patient intake — Symptoms: ${intakeSummary?.symptoms || "not specified"}, Severity: ${intakeSummary?.severity || "unknown"}, Duration: ${intakeSummary?.duration || "unknown"}.
${chatMessages && chatMessages.length > 0 ? `Chat history:\n${chatMessages.map(m => `${m.role}: ${m.content}`).join("\n")}` : "No chat messages recorded."}
Return ONLY JSON: {"chiefComplaint":"...","keySymptoms":[],"recommendations":[],"followUp":"...","urgency":"low|medium|high"}`
            }
          ],
          intakeSummary,
          forceSummary: true,
        }),
      });
      const data = await res.json();
      if (data.summary) {
        setSummary(data.summary);
      } else {
        // Parse from reply if summary not in data
        try {
          const parsed = JSON.parse(data.reply.replace(/```json|```/g, "").trim());
          setSummary(parsed);
        } catch {
          setSummary({
            chiefComplaint: intakeSummary?.symptoms || "General consultation",
            keySymptoms: [],
            recommendations: ["Please consult your doctor for a detailed treatment plan."],
            followUp: "Schedule a follow-up within 1 week.",
            urgency: intakeSummary?.severity === "severe" ? "high" : intakeSummary?.severity === "moderate" ? "medium" : "low",
          });
        }
      }
    } catch {
      setSummary({
        chiefComplaint: intakeSummary?.symptoms || "General consultation",
        keySymptoms: [],
        recommendations: ["Please consult your doctor for a detailed treatment plan."],
        followUp: "Schedule a follow-up within 1 week.",
        urgency: "low",
      });
    } finally {
      setGenerating(false);
    }
  };

  if (showSummary) {
    return (
      <div style={{ width: "100%", height: "100%", overflowY: "auto", padding: "24px", boxSizing: "border-box" }}>
        <div style={{ maxWidth: 480, margin: "0 auto" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 20 }}>
            <div style={{ width: 40, height: 40, borderRadius: "50%", background: "#0ea5e922", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 20 }}>📋</div>
            <div>
              <div style={{ fontWeight: 700, fontSize: 16 }}>Consultation Summary</div>
              <div style={{ fontSize: 12, color: "var(--text-2)" }}>Generated by MedLive AI</div>
            </div>
          </div>

          {generating ? (
            <div style={{ textAlign: "center", padding: "40px 0", color: "var(--text-2)" }}>
              <div className="typing-indicator" style={{ justifyContent: "center", marginBottom: 12 }}>
                <div className="typing-dot" /><div className="typing-dot" /><div className="typing-dot" />
              </div>
              Generating your consultation summary...
            </div>
          ) : summary ? (
            <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>

              {/* Urgency Badge */}
              <div style={{ display: "flex", justifyContent: "flex-end" }}>
                <span style={{
                  fontSize: 12, fontWeight: 700, padding: "4px 12px", borderRadius: 20,
                  background: urgencyColor[summary.urgency] + "22",
                  color: urgencyColor[summary.urgency],
                  border: `1px solid ${urgencyColor[summary.urgency]}44`,
                }}>
                  {summary.urgency.toUpperCase()} URGENCY
                </span>
              </div>

              {/* Chief Complaint */}
              <div style={{ padding: 14, background: "var(--surface2)", borderRadius: 10, border: "1px solid var(--border)" }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-2)", marginBottom: 4, textTransform: "uppercase", letterSpacing: 1 }}>Chief Complaint</div>
                <div style={{ fontSize: 14 }}>{summary.chiefComplaint}</div>
              </div>

              {/* Key Symptoms */}
              {summary.keySymptoms.length > 0 && (
                <div style={{ padding: 14, background: "var(--surface2)", borderRadius: 10, border: "1px solid var(--border)" }}>
                  <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-2)", marginBottom: 8, textTransform: "uppercase", letterSpacing: 1 }}>Key Symptoms</div>
                  <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                    {summary.keySymptoms.map((s, i) => (
                      <span key={i} style={{ fontSize: 12, padding: "4px 10px", background: "#0ea5e922", color: "#0ea5e9", borderRadius: 20, border: "1px solid #0ea5e933" }}>{s}</span>
                    ))}
                  </div>
                </div>
              )}

              {/* Recommendations */}
              {summary.recommendations.length > 0 && (
                <div style={{ padding: 14, background: "var(--surface2)", borderRadius: 10, border: "1px solid var(--border)" }}>
                  <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-2)", marginBottom: 8, textTransform: "uppercase", letterSpacing: 1 }}>Recommendations</div>
                  {summary.recommendations.map((r, i) => (
                    <div key={i} style={{ display: "flex", gap: 8, marginBottom: 6, fontSize: 13 }}>
                      <span style={{ color: "#22c55e", fontWeight: 700, flexShrink: 0 }}>✓</span>
                      <span>{r}</span>
                    </div>
                  ))}
                </div>
              )}

              {/* Follow-up */}
              <div style={{ padding: 14, background: "var(--surface2)", borderRadius: 10, border: "1px solid var(--border)" }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: "var(--text-2)", marginBottom: 4, textTransform: "uppercase", letterSpacing: 1 }}>Follow-up</div>
                <div style={{ fontSize: 14 }}>📅 {summary.followUp}</div>
              </div>

              {/* Disclaimer */}
              <div style={{ fontSize: 11, color: "var(--text-2)", textAlign: "center", padding: "8px 0", borderTop: "1px solid var(--border)" }}>
                ⚠️ AI-generated summary — not a medical diagnosis. Consult a licensed doctor.
              </div>

              {/* New Consultation Button */}
              <button
                className="launch-btn"
                onClick={() => { setShowSummary(false); setSummary(null); }}
                style={{ marginTop: 4 }}
              >
                Start New Consultation
              </button>
            </div>
          ) : null}
        </div>
      </div>
    );
  }

  return (
    <div style={{ width: "100%", height: "100%", position: "relative" }}>
      {agentId && agentUrl ? (
        <>
          <iframe
            src={agentUrl}
            allow="camera; microphone; fullscreen; autoplay; speaker-selection"
            style={{ width: "100%", height: "100%", border: "none" }}
          />
          {/* End Call Button */}
          <button
            onClick={handleEndCall}
            style={{
              position: "absolute", bottom: 20, left: "50%", transform: "translateX(-50%)",
              background: "#ef4444", color: "white", border: "none", borderRadius: 24,
              padding: "10px 24px", fontWeight: 700, fontSize: 13, cursor: "pointer",
              display: "flex", alignItems: "center", gap: 8, boxShadow: "0 4px 12px #ef444466",
              zIndex: 10,
            }}
          >
            📋 End Call & Get Summary
          </button>
        </>
      ) : (
        <div className="video-placeholder">
          <div className="logo-mark" style={{ width: 64, height: 64, borderRadius: "50%" }}>
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ width: 32, height: 32 }}>
              <path d="M22 12h-4l-3 9L9 3l-3 9H2" />
            </svg>
          </div>
          <h2>Initialize Video Engine</h2>
          <p>Launch the real-time clinical assessment agent. System telemetry will sync automatically.</p>
          <button className="launch-btn" onClick={onLaunch} disabled={isLoading}>
            {isLoading ? "Synchronizing..." : "Start Professional Consultation"}
          </button>
          {errorMessage && <p className="launch-error">{errorMessage}</p>}
        </div>
      )}
    </div>
  );
}